### PR TITLE
Make hello_world example for AOSP

### PR DESCRIPTION
**Pull request by nkh-lab**
Signed-off-by: Nikolay Khilyuk <nkh@ua.fm>

### CODE REVIEW

**Comment by AnaBit** [comment]
How did you compile the boost source code in aosp?

**Comment by nkh-lab** [comment]
> How did you compile the boost source code in aosp?

Via created corresponding Android.bp build script.

**Comment by jayhou** [comment]
@AnaBit https://github.com/moritz-wundke/Boost-for-Android   this may help you.

**Comment by nkh-lab** [comment]
> @AnaBit https://github.com/moritz-wundke/Boost-for-Android this may help you.

I don't think so. Mentioned project supports boost for NDK not AOSP. If you use compiled libraries like prebuilt in AOSP you will have namespace issues due to NDK and AOSP use different STL libraries.

**Comment by jayhou** [comment]
@nkh-lab you are right, but I found AOSP can also use ndk to compile, just add sdk_version: "**" in the Android.bp file , so it's works for me right now, though it's not elegent enought. Your method is the great.

**Comment by lutzbichler** [comment]
Merged to v3.1.14.1

**Pull request closed without merging**
