### PR TITLE
Added doxygen documentation for the public API

### PR DESCRIPTION
**Pull request by drivingThrillhouse**
This change adds some initial documentation for the API so that new users get an idea what to call in order to get things working.

* Added module "Application" including vsomeip::application
* Added module "Runtime" including vsomeip::runtime

### CODE REVIEW

**Comment by jeremiah** [comment]
Thanks for the contribution! Can I ask that you add a signed-off by line to the request? Thanks!

I'll contact the maintainer to see about landing these patches.

**Comment by drivingThrillhouse** [comment]
Can you tell me what your signed-off-by policy is? I need to check if I need to do something inside my company before being allowed to add the signed-off-by.

**Comment by jeremiah** [comment]
In a nutshell GENIVI needs to know that you are allowed to make this contribution much like you would if you were contributing to the Linux kernel or other open source projects. In fact our process is pretty much just a copy of the kernel's process. 

Here is more detail on what we want in the signed-off-by line: https://at.projects.genivi.org/wiki/display/PROJ/How+to+contribute+to+GENIVI#HowtocontributetoGENIVI-PullrequestthroughGithub

You're company or whomever holds copyright on your contribution won't have to do anything more than provide permission for you to contribute these changes and that permission is evidenced by the signed-off-by line.

**Comment by GenivivSOMEIPmaintainer** [comment]
The changes were merged outside this repository.

**Pull request closed without merging**
